chain: {fixed_params: cosmo, mcmc_type: normal, nburn: 0, nsteps: 100000, nwalkers: 250,
  seed: 0}
data:
  cov:
    emu_cov_fname: &id001 [/u/ki/swmclau2/Git/pearce/bin/optimization/wp_hod_emu_cov_lpw.npy,
      /u/ki/swmclau2/Git/pearce/bin/optimization/ds_hod_emu_cov_lpw.npy]
    meas_cov_fname: /u/ki/swmclau2/Git/pearce/bin/covmat/wp_ds_full_covmat.npy
  obs:
    mean: false
    obs: [wp, ds]
    rbins:
    - !!python/object/apply:numpy.core._multiarray_umath.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        mpmZmZmZuT8=
    - !!python/object/apply:numpy.core._multiarray_umath.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        LJ5XOMXZwT8=
    - !!python/object/apply:numpy.core._multiarray_umath.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        MNKF3OzkyD8=
    - !!python/object/apply:numpy.core._multiarray_umath.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        19amkslb0T8=
    - !!python/object/apply:numpy.core._multiarray_umath.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        F4MiQTs12D8=
    - !!python/object/apply:numpy.core._multiarray_umath.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        7FBwEEfh4D8=
    - !!python/object/apply:numpy.core._multiarray_umath.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        QbcOoGGK5z8=
    - !!python/object/apply:numpy.core._multiarray_umath.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        aQuDLiVq8D8=
    - !!python/object/apply:numpy.core._multiarray_umath.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        k48Dyj3k9j8=
    - !!python/object/apply:numpy.core._multiarray_umath.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        sLhbLZjs/z8=
    - !!python/object/apply:numpy.core._multiarray_umath.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        XUH9gK5CBkA=
    - !!python/object/apply:numpy.core._multiarray_umath.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        QfX0NUkLD0A=
    - !!python/object/apply:numpy.core._multiarray_umath.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        yVqUcZOlFUA=
    - !!python/object/apply:numpy.core._multiarray_umath.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        rGEUYjAwHkA=
    - !!python/object/apply:numpy.core._multiarray_umath.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        gviFLM0MJUA=
    - !!python/object/apply:numpy.core._multiarray_umath.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        RZcm2yFbLUA=
    - !!python/object/apply:numpy.core._multiarray_umath.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        JKFpID14NEA=
    - !!python/object/apply:numpy.core._multiarray_umath.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        O7n8//KLPEA=
    - !!python/object/apply:numpy.core._multiarray_umath.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        rYSTk8XnQ0A=
  sim: &id002
    cosmo_params: {H0: 65.7317, Neff: 3.2, ns: 0.971515, ombh2: 0.022762900000000003,
      omch2: 0.11283, sigma8: 0.7542319000000001, w0: -0.861513}
    gal_type: HOD
    hod_name: hsabZheng07
    hod_params: {alpha: 1.083, conc_gal_bias: 1.0, logM0: 13.2, logM1: 14.2, mean_occupation_centrals_assembias_param1: 1.0,
      mean_occupation_satellites_assembias_param1: -1.0, sigma_logM: 0.2}
    min_ptcl: 100
    nd: 5e-4
    scale_factor: 1.0
    sim_hps: {boxno: 1, downsample_factor: 0.01, particles: true, realization: 1,
      sec_haloprop_key: halo_nfw_conc, system: ki-ls}
    simname: testbox
  true_cov_fname: /u/ki/swmclau2/Git/pearce/bin/covmat/wp_ds_full_covmat.npy
emu:
  emu_cov_fname: *id001
  emu_hps: {}
  emu_type: [LemonPepperWet, LemonPepperWet]
  fixed_params: {rmin: 1.0, z: 0.0}
  training_file: [/u/ki/swmclau2/des/Aemulators/wp_zheng07/PearceWpCosmo.hdf5, /u/ki/swmclau2/des/Aemulators/ds_zheng07/PearceDsCosmo.hdf5]
fname: /u/ki/swmclau2/des/PearceMCMC/CAB_HOD_fixed_cosmo_nfw_conc_wp_ds_rmin_1.0_HOD.hdf5
sim: *id002
