chain:
  fixed_params: {}
  mcmc_type: normal
  nburn: 0
  nsteps: 50000
  nwalkers: 200
  seed: 0
data:
  cov:
    emu_cov_fname: &id002 [/home/users/swmclau2/Git/pearce/bin/optimization/wp_hsab_emu_cov_lpw.npy,
      /home/users/swmclau2/Git/pearce/bin/optimization/ds_hsab_emu_cov_lpw.npy]
    meas_cov_fname: /home/users/swmclau2/Git/pearce/bin/covmat/wp_ds_full_covmat.npy
  obs:
    mean: false
    obs: [wp, ds]
    rbins:
    - !!python/object/apply:numpy.core.multiarray.scalar
      - &id001 !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        mpmZmZmZuT8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        LJ5XOMXZwT8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        MNKF3OzkyD8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        19amkslb0T8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        F4MiQTs12D8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        7FBwEEfh4D8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        QbcOoGGK5z8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        aQuDLiVq8D8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        k48Dyj3k9j8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        sLhbLZjs/z8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        XUH9gK5CBkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        QfX0NUkLD0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        yVqUcZOlFUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        rGEUYjAwHkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        gviFLM0MJUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        RZcm2yFbLUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        JKFpID14NEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        O7n8//KLPEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        rYSTk8XnQ0A=
  sim: &id003
    gal_type: HOD
    hod_name: zheng07
    hod_params: {alpha: 1.083, conc_gal_bias: 1.0, logM0: 13.2, logM1: 14.2, sigma_logM: 0.2}
    min_ptcl: 100
    nd: 5e-4
    scale_factor: 1.0
    sim_hps: {boxno: 1, downsample_factor: 0.01, particles: true, realization: 0,
      system: sherlock}
    simname: testbox
emu:
  emu_cov_fname: *id002
  emu_hps: {}
  emu_type: [LemonPepperWet, LemonPepperWet]
  fixed_params: {rmin: 0.5, z: 0.0}
  training_file: [/home/users/swmclau2/scratch/wp_hsab/PearceWpHSABCosmo.hdf5, /home/users/swmclau2/scratch/ds_hsab/PearceDsHSABCosmo.hdf5]
fname: /home/users/swmclau2/scratch/PearceMCMC/HOD_wp_ds_rmin_0.5_HSAB.hdf5
sim: *id003
