chain:
  fixed_params: {}
  mcmc_type: normal
  nburn: 0
  nsteps: 100000
  nwalkers: 250
  seed: 0
data:
  cov:
    emu_cov_fname: &id002 [/home/users/swmclau2/Git/pearce/bin/optimization/wp_corrab_emu_cov_lpw.npy,
      /home/users/swmclau2/Git/pearce/bin/optimization/ds_corrab_emu_cov_lpw.npy]
    meas_cov_fname: /home/users/swmclau2/Git/pearce/bin/covmat/wp_ds_full_covmat.npy
  obs:
    mean: false
    obs: [wp, ds]
    rbins:
    - !!python/object/apply:numpy.core.multiarray.scalar
      - &id001 !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        mpmZmZmZuT8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        LJ5XOMXZwT8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        MNKF3OzkyD8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        19amkslb0T8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        F4MiQTs12D8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        7FBwEEfh4D8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        QbcOoGGK5z8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        aQuDLiVq8D8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        k48Dyj3k9j8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        sLhbLZjs/z8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        XUH9gK5CBkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        QfX0NUkLD0A=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        yVqUcZOlFUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        rGEUYjAwHkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        gviFLM0MJUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        RZcm2yFbLUA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        JKFpID14NEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        O7n8//KLPEA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        rYSTk8XnQ0A=
  sim:
    gal_type: SHAM
    halo_property: halo_vpeak
    min_ptcl: 100
    nd: 5e-4
    scale_factor: 1.001
    scatter: 0.2
    sim_hps: {system: sherlock}
    simname: ds_14_b_sub
  true_cov_fname: /home/users/swmclau2/Git/pearce/bin/covmat/wp_ds_full_covmat.npy
  true_data_fname: [/home/users/swmclau2/Git/pearce/bin/mock_measurements/UMmock_wp.npy,
    /home/users/swmclau2/Git/pearce/bin/mock_measurements/UMmock_ds.npy]
emu:
  emu_cov_fname: *id002
  emu_hps: {}
  emu_type: [LemonPepperWet, LemonPepperWet]
  fixed_params: {rmin: 2.0, z: 0.0}
  training_file: [/home/users/swmclau2/scratch/wp_corrab/PearceWpCorrABCosmo.hdf5,
    /home/users/swmclau2/scratch/ds_corrab/PearceDsCorrABCosmo.hdf5]
fname: /home/users/swmclau2/scratch/PearceMCMC/UniverseMachine_wp_ds_rmin_2.0_CorrAB.hdf5
